name: Template Cleanup
on:
  push:
    branches:
      - main

jobs:

  # Run cleaning process only if workflow is triggered by the template repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.repository.name != 'dropwizard-template'
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Cleanup project
      - name: Cleanup
        run: |
          export LC_CTYPE=C
          export LANG=C

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.nduckett.$SAFE_NAME"

          # Replace placeholders in the template-cleanup files
          sed -i "s/%NAME%/$NAME/g" .github/template-cleanup/*
          sed -i "s/%REPOSITORY%/${GITHUB_REPOSITORY/\//\\/}/g" .github/template-cleanup/*
          sed -i "s/%GROUP%/$GROUP/g" .github/template-cleanup/*

          # Replace template package name in project files with $GROUP
          find src -type f -exec sed -i "s/com.companyname.template/$GROUP/g" {} +
          find src -type f -exec sed -i "s/Template/$NAME/g" {} +

          # Move content
          mkdir -p src/main/java/${GROUP//.//}
          mkdir -p src/test/java/${GROUP//.//}
          cp -R .github/template-cleanup/* .
          cp -R src/main/java/com/companyname/template/* src/main/java/${GROUP//.//}/
          cp -R src/test/java/com/companyname/template/* src/test/java/${GROUP//.//}/

          # Cleanup
          rm -rf \
            .github/ISSUE_TEMPLATE \
            .github/readme \
            .github/template-cleanup \
            .github/workflows/template-cleanup.yml \
            .idea/icon.png \
            src/main/java/com/companyname/template \
            src/test/java/com/companyname/template \

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}